version: '3.8'

services:
  redis:
    container_name: redis_rest_client
    image: redis
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    restart: always

volumes:
  redis:
    driver: local
